kind: Pod
apiVersion: v1
metadata:
  name: evx-root
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: data
  volumes:
    - name: data
      csi:
        driver: auristorfs.csi.auristor.com
        volumeAttributes:
          mount-type: root
