kind: Pod
apiVersion: v1
metadata:
  name: evx
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: data
  volumes:
    - name: data
      csi:
        driver: auristorfs.csi.auristor.com
        volumeAttributes:
          cell-name:  auristor.com
          volume-name: k8s.demo          
