#!/bin/bash

RELEASE_VERSION=${RELEASE_VERSION:-"2022.02.1"}

echo === Deploying Auristor Special Resource ===

oc get namespace auristorfs-client >> /dev/null

 if [ "$?" -ne 0 ]; then
  echo ERROR: Namespace does not exists, not deploying SpecialResource
  exit 1
fi 

# Create ConfigMap object
oc create -n auristorfs-client cm auristor-client-chart --from-file=charts/cm/index.yaml --from-file=charts/cm/auristor-client-$RELEASE_VERSION.tgz 

oc create -f charts/auristor-client.yaml
