#!/bin/bash
echo === Deploying Auristor Special Resource ===

echo 1: $1

NAMESPACE=${1:-"auristor-client"}

echo NAMESPACE: $NAMESPACE

while true ;
do
    foo=$( oc get specialresource auristor-client  | wc -l)

    if [ "$foo" -gt "0" ]; then
        echo waiting for specialresource/auristor-client to terminate
        sleep 2
    else
        break
    fi
done

# Create namespace 
if oc get namespace auristor-client >/dev/null; then
  echo namespace auristor-client already exists
else
  oc create namespace auristor-client 
fi 

# Create ConfigMap object
oc delete -n $NAMESPACE cm auristor-client-chart --ignore-not-found=true
oc create -n $NAMESPACE cm auristor-client-chart --from-file=charts/cm/index.yaml --from-file=charts/cm/auristor-client-0.0.1.tgz 


oc create -n $NAMESPACE -f charts/auristor-client.yaml
