apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auristorfs-csi-extra-permission-cr
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - csistoragecapacities
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments/status
    verbs:
      - patch
