#!/bin/bash

echo === Undeploying Auristor Special Resource ===

oc delete specialresource auristor-client --ignore-not-found=true
oc delete cm  -n auristor-xyz auristor-client-chart --ignore-not-found=true


