kind: Pod
apiVersion: v1
metadata:
  name: svx
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: web
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-svx
