apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: auristorfs-client
spec:
  namespace: auristorfs-client

  chart:
    name: auristorfs-client
    version: 0.0.5
    repository:
      name: auristorfs-client-chart
      url: cm://auristorfs-client/auristorfs-client-chart

  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["yfs"]

    runArgs:
      platform: "openshift-container-platform"

    kmodDriverContainer:
      image:
        auristorRegistry: "ghcr.io/auristor"
        auristorKmodVersion: "2021.05-20"
        kmodImagePullPolicy: Always
        terminationGracePeriodSeconds: 2

      mapVolumes:
        - label: yfs-cache
          target: /var/cache/yfs
          hostPath: 
            path: /var/cache/yfs
            
        - label: etc-yfs
          target: /etc/yfs
          configMap:
            name: etc-yfs

        - label: usr-share-yfs
          target: /usr/share/yfs
          configMap:
            name: usr-share-yfs

        # - label: etc-yfs-keytabs
        #   target: /etc/yfs-keytabs
        #   secret:
        #     name: etc-yfs-keytabs
        
        - label: etc-yfs-keytabs
          target: /etc/yfs-keytabs
          hostPath:
            path: /etc/yfs-keytabs           


    csiDriver:
      image:       ###   Registry and Version Values
        auristorRegistry: ghcr.io/auristor
        auristorCsiVersion: 2022.02-2
        csiDriverImagePullPolicy: Always
        k8sSigStorageRegistry: k8s.gcr.io/sig-storage
        k8sSigStorageImagePullPolicy: Always


      cacheManager:       ###  Cache Manager Values
        defaultCacheManager: auristor

      logging:
        logLevel: INFO  # (DEBUG, INFO, WARNING, ERROR, or FATAL)
