#!/bin/bash

oc delete -n $SPECIAL_RESOURCE_NAMESPACE cm etc-yfs 2>/dev/null

oc delete -n $SPECIAL_RESOURCE_NAMESPACE cm usr-share-yfs  2>/dev/null

oc delete -n $SPECIAL_RESOURCE_NAMESPACE secret etc-yfs-keytabs  2>/dev/null