#!/bin/bash

SPECIAL_RESOURCE_NAMESPACE=auristorfs-client

oc delete -n $SPECIAL_RESOURCE_NAMESPACE cm etc-yfs 

oc delete -n $SPECIAL_RESOURCE_NAMESPACE cm usr-share-yfs

oc delete -n $SPECIAL_RESOURCE_NAMESPACE secret etc-yfs-keytabs