apiVersion: v1
entries:
  auristor-client:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-10-29T20:26:50.917240262-04:00"
    description: AuriStor Client kmod (and eventually ALS and CSI)
    digest: 7e288c8d3c6f51b2e2508bc2c2be6b7ff8f0b9e856b7ba2dcd2ac6475e09db33
    icon: https://avatars.githubusercontent.com/u/55542927
    name: auristor-client
    type: application
    urls:
    - cm://auristor-client/auristor-client-chart/auristor-client-0.0.1.tgz
    version: 0.0.1
generated: "2021-10-29T20:26:50.91634103-04:00"
