apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: auristor-client
spec:
  namespace: auristor-client
  debug: false
  chart:
    name: auristor-client
    version: 0.0.1
    repository:
      name: example
      url: cm://auristor-client/auristor-client-chart
      # It is possible to deploy from local files instead of creating ConfigMap
      # This approach is not recommended
      # url: file:///charts
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["yfs"]
    buildArgs:
    - name: "KMOD_SOFTWARE_VERSION"
      value: "\"2021.05\""
    - name: "KMOD_RELEASE"
      value: "\"12\""
  driverContainer:
    source:
      git:
        # uri: "https://github.com/GerrySeidman/kvc-auristor-client.git"
        # ref: "fixing-repo"
        uri: "https://github.com/dariaphoebe/kvc-auristor-client.git"
        ref: "main"
    # artifacts:
    #   hostpaths:
    #     - sourcePath: "/tmp/sro-artifact"
    #     - destinationDir: "/tmp/sro-artifact"
