apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: auristor-client
spec:
  namespace: auristor-xyz
  debug: false
  chart:
    name: auristor-client
    version: 0.0.1
    repository:
      name: example
      url: cm://auristor-xyz/auristor-client-chart
      # It is possible to deploy from local files instead of creating ConfigMap
      # This approach is not recommended
      # url: file:///charts
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["yfs"]
    auristorRegistry: "ghcr.io/auristor"
    auristorVersion: "2021.05-15"
    
    runArgs:
      platform: "openshift-container-platform"
    kmodDriverContainer:
      auristorRegistry: "ghcr.io/auristor"
      auristorKmodVersion: "2021.05-15"
      terminationGracePeriodSeconds: 3
      yfsCache: /var/cache/yfs
      directories:
        - label: etc-yfs
          target: /etc/yfs
          files:
            yfs-client.conf: |
              # This Comment is required (at this indenting) to satisfy helm indenting
                  # Insert yfs-client.conf contents here (at this indenting)

                  # This merges the grand.central.org [cells] section:
                  include /usr/share/yfs/cellservdb.conf
                  # includedir /etc/yfs/yfs-client.conf.d

                  [defaults]
                  # You need to set a thiscell here
                    thiscell = your-file-system.com

                  [afsd]
                      blocks = 100000
                      debug = yes
                      # memcache = yes
                      nomount = yes

                  [cells]
                  # You may define your own cells here.
            other: |
              # This Comment is required (at this indenting) to satisfy helm indenting
                  # Insert yfs-client.conf contents here (at this indenting)
                  This is something else      
        - label: usr-share-yfs
          target: /usr/share/yfs
          files:
            cellservdb.conf: |
              # This Comment is required (at this indenting) to satisfy helm indenting
                  # AuriStorFS cellservdb client configuration
                  # 1 March 2021
                  #
                  # This file should be placed in the yfs-client.conf.d directory
                  # or be included from within the yfs-client.conf file.

                  [cells]
                    # umich.edu imported from AFSDB
                    umich.edu = {
                      description = "University of Michigan - Campus"
                      use_dns = yes
                      servers = {
                        fear.ifs.umich.edu = {
                          address = 141.211.1.32
                        }
                        surprise.ifs.umich.edu = {
                          address = 141.211.1.33
                        }
                        ruthless.ifs.umich.edu = {
                          address = 141.211.1.34
                        }
                      }
                    }

    csiDriver:
      auristorCsiVersion: 2022-02.1
      csiDriverImage: ghcr.io/auristor/auristor-csi:2022-02.1
      csiDriverImagePullPolicy: Always
      k8sSigStorageRegistry: k8s.gcr.io/sig-storage
      auristorRegistry: ghcr.io/auristor

      defaultCacheManager: auristor
      afsRootDir: null
      nodeSelector: none   


      externalVolumeManagerURL: http://auristorfs-volume-manager       ## Default implementation provided

      logLevel: DEBUG                      # Log level for all components (DEBUG, INFO, WARNING, ERROR, or FATAL)
      flattenLog: "false"                   # Set to true to fold all logging messages to one line (in particular stack traces, though it makes them harder to read)

      ## Validate AuristorFS volume status during CSI phase
      controllerCreateVolumeValidation: None    # 	None, Exists, or Online
      controllerPublishVolumeValidation: None   # 	None, Exists, or Online
      nodeStageVolumeValidation: None           # 	None, Exists, or Online
      nodePublishVolumeValidation: None         # 	None, Exists, or Online

      # Values which affect PV and volumeHandle names
      volumeNamePrefix: afs              # PV Name Prefix
      volumeNameUuidLength: "-1"         # Shortens PV names which is useful during debugging
      pvUIDLength: "10"                  # Shortens internal PVHandle name which is useful during debugging

      # Debugging Options
      debugShowCsiRequests: "false"
      debugShowMounts: "true"
      debugShowExecs: "true"

      defaultFileServerHost: fs1.example.com
      defaultFileServerPartition: a
###   Registry and Version Values
      image:
        auristorRegistry: ghcr.io/auristor
        auristorCsiVersion: 2022-02.1
        csiDriverImagePullPolicy: Always
        k8sSigStorageRegistry: k8s.gcr.io/sig-storage
        k8sSigStorageImagePullPolicy: Always

    ###  Cache Manager Values
      cacheManager:
        defaultCacheManager: auristor
        # afsRootDir: "/afs"              # Set to dynamic AFS root (typically /afs) or null if not pre-loaded (ie in OpenShift).  afsRootDir is not used if defaultCacheManager=kafs

    ### Logging Values
      logging:
        logLevel: DEBUG                       # Log level for all components (DEBUG, INFO, WARNING, ERROR, or FATAL)
        flattenLog: "false"                   # Set to true to fold all logging messages to one line (in particular stack traces, though it makes them harder to read)

    ### External Volume Manager Values
      microServices:
        externalVolumeManagerURL: http://auristorfs-volume-manager       ## Default implementation provided

      ## ExternalVolumeManager AuristorFS volume status/validation during CSI phase
      externalVolumeManager:
        persistentVolumeReadyToCreateValidation: None                 #	None, Exists, or Online
        persistentVolumeReadyToAttachOntoNodeValidation: None         #	None, Exists, or Online
        persistentVolumeReadyForFirstConsumerOnNodeValidation: None   #	None, Exists, or Online
        persistentVolumeReadyToMountOntoPodResponseValidation: None   #	None, Exists, or Online

    # PV naming Values
      persistentVolumeNaming:
        volumeNamePrefix: afs              # PV Name Prefix (used by csi-provisioner sidecar)

    # Debugging Values
      debug:
        debugging: false            
        # debugShowCsiRequests: "false"
        # debugShowMounts: "false"
        # debugShowExecs: "false"
        # pvUIDLength: "10"                  # Shortens internal PVHandle name which is useful during debugging
        # volumeNameUuidLength: ""            # Shortens PV names which is useful during debugging (used by csi-provisioner sidecar)      

  driverContainer:
    source:
      git:
        # uri: "https://github.com/GerrySeidman/kvc-auristor-client.git"
        # ref: "fixing-repo"
        uri: "https://github.com/dariaphoebe/kvc-auristor-client.git"
        ref: "main"
    # artifacts:
    #   hostpaths:
    #     - sourcePath: "/tmp/sro-artifact"
    #     - destinationDir: "/tmp/sro-artifact"
