apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: auristor-client
spec:
  namespace: auristorfs-client

  chart:
    name: auristor-client
    version: 0.0.1
    repository:
      name: example
      url: cm://auristorfs-client/auristor-client-chart
      
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["yfs"]

    runArgs:
      platform: "openshift-container-platform"
      
    kmodDriverContainer:
      auristorRegistry: "ghcr.io/auristor"
      auristorKmodVersion: "2021.05-15"
      terminationGracePeriodSeconds: 2
      yfsCache: /var/cache/yfs
      mapVolumes:
        - label: etc-yfs
          target: /etc/yfs
          configMap:
            configMapName: etc-yfs        

        - label: usr-share-yfs
          target: /usr/share/yfs
          configMap:
            configMapName: usr-share-yfs

        - label: etc-yfs-keytabs
          target: /etc/yfs-keytabs
          secret:
            secretName: etc-yfs-keytabs

    csiDriver:

      ###   Registry and Version Values
      image:
        auristorRegistry: ghcr.io/auristor
        auristorCsiVersion: 2022-02.1
        csiDriverImagePullPolicy: Always
        k8sSigStorageRegistry: k8s.gcr.io/sig-storage
        k8sSigStorageImagePullPolicy: Always

      ###  Cache Manager Values
      cacheManager:
        defaultCacheManager: auristor

      ### Logging Values
      logging:
        logLevel: DEBUG                       # Log level for all components (DEBUG, INFO, WARNING, ERROR, or FATAL)
