specialresource:
  metadata:
    name: auristorfs
  spec:
    namespace: auristorfs-client
    
groupName:
  csiDriver: csi-driver   

runArgs:
  platform: "kubernetes"  

csiDriver:
  image:       ###   Registry and Version Values
    auristorRegistry: ghcr.io/auristor
    auristorCsiVersion: 2022.02-2
    csiDriverImagePullPolicy: Always
    k8sSigStorageRegistry: k8s.gcr.io/sig-storage
    k8sSigStorageImagePullPolicy: Always

  
  cacheManager:       ###  Cache Manager Values
    defaultCacheManager: auristor
    afsRootDir: "/afs"  ##  AFS Root on node

  logging:
    logLevel: INFO  # (DEBUG, INFO, WARNING, ERROR, or FATAL)