
#######################################
### Auristor CSI Roles and Bindings ###
#######################################

##################################
### External Provisioner Roles ###
##################################

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-provisioner-cr
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-provisioner-r
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
# Permissions for CSIStorageCapacity are only needed enabling the publishing
# of storage capacity information.
- apiGroups: ["storage.k8s.io"]
  resources: ["csistoragecapacities"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# The GET permissions below are needed for walking up the ownership chain
# for CSIStorageCapacity. They are sufficient for deployment via
# StatefulSet (only needs to get Pod) and Deployment (needs to get
# Pod and then ReplicaSet to find the Deployment).
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get"]

---
#################################
###  External Attacher Roles  ###
#################################


kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-attacher-cr
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-attacher-r
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
##################################
###  Controller Role Bindings  ###
##################################

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-provisioner-rb
subjects:
  - kind: ServiceAccount
    name: auristorfs-csi
    namespace: auristorfs-client
roleRef:
  kind: Role
  name: auristorfs-csi-external-provisioner-r
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-provisioner-crb
subjects:
  - kind: ServiceAccount
    name: auristorfs-csi
    namespace: auristorfs-client
roleRef:
  kind: ClusterRole
  name: auristorfs-csi-external-provisioner-cr
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-attacher-crb
subjects:
  - kind: ServiceAccount
    name: auristorfs-csi
    namespace: auristorfs-client
roleRef:
  kind: ClusterRole
  name: auristorfs-csi-external-attacher-cr
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auristorfs-csi-external-attacher-role-rb
subjects:
  - kind: ServiceAccount
    name: auristorfs-csi
    namespace: auristorfs-client
roleRef:
  kind: Role
  name: auristorfs-csi-external-attacher-r
  apiGroup: rbac.authorization.k8s.io
