apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-dvx
  labels:
      demo: auristor
provisioner: auristorfs.csi.auristor.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  cell-name:  auristor.com
  volume-name: k8s.demo