apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-dvx
provisioner: auristorfs.csi.auristor.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  cell-name:  your-file-system.com
  volume-name: root.cell
  creatable: "false"