apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-dvx-root
  labels:
      demo: auristor
provisioner: auristorfs.csi.auristor.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  mount-type: root
