#!/usr/bin/env bash

SRO_MANAGER_POD=$(oc get pod -n openshift-special-resource-operator -o name | grep special-resource-controller-manager | head -1)

# WATCH='-f --tail=4'

WATCH=${WATCH:-'-f --tail=4'}

clear
oc logs $WATCH -n openshift-special-resource-operator $SRO_MANAGER_POD -c manager $2 $3 $4 $5

