#!/usr/bin/env bash

SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
APP_ROOT=$( cd $SCRIPTPATH/.. ; pwd -P )

watch "    echo --- DAEMONSETS --- \
        && oc get daemonsets  -n $SPECIAL_RESOURCE_NAMESPACE -o name \
        && echo '' \
        && echo ---- PODS ---\
        && oc get pod -n $SPECIAL_RESOURCE_NAMESPACE -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName,IP:.status.podIP \
        && echo '' \
        && $SCRIPTPATH/kmodReport
      "