apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pvx
  labels:
    volume: pv-pvx
spec:
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Mi    # IGNORED
  csi:
    driver: auristorfs.csi.auristor.com
    volumeHandle: your-volume-pvx
    volumeAttributes:               # Attributes of the volume to publish. 
      cell-name:  "your-cell-name.com"
      volume-name: "your-volume"
      creatable: "false"