{{- if ne .Values.runArgs.platform "openshift-container-platform" }}
---
{{ end }}
####################################
###    Auristor CSI Controller   ###
####################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: auristorfs-csi-controller-config
data:
  {{ if .Values.csiDriver.microServices }}
  externalVolumeManagerURL: {{ .Values.csiDriver.microServices.externalVolumeManagerURL }}   
  {{ else }}
  externalVolumeManagerURL: "http://auristorfs-volume-manager"  
  {{ end }}

  defaultCacheManager: {{ .Values.csiDriver.cacheManager.defaultCacheManager }}    # kafs or auristor

  logLevel: {{ .Values.csiDriver.logging.logLevel | default "INFO" | quote }}  
  flattenLog: {{ .Values.csiDriver.logging.flattenLog | default "false" | quote }}  
  

  {{ if .Values.csiDriver.debug }}
  # Debugging Values
  pvUIDLength: {{ .Values.csiDriver.debug.pvUIDLength | default "10" | quote }} 
  debugShowCsiRequests: {{ .Values.csiDriver.debug.debugShowCsiRequests | default "false" | quote }} 
  debugShowMounts: {{ .Values.csiDriver.debug.debugShowMounts | default "false" | quote }} 
  debugShowExecs: {{ .Values.csiDriver.debug.debugShowExecs | default "false" | quote }} 
  {{ end }}
---

apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
 name: auristorfs.csi.auristor.com
spec:
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  podInfoOnMount: true
  attachRequired: true

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: auristorfs-csi-controller
spec:
  serviceName: auristorfs-csi-svc
  replicas: 1
  selector:
    matchLabels:
      app: auristorfs-csi-controller
  template:
    metadata:
      labels:
        app: auristorfs-csi-controller
    spec:
      serviceAccountName: auristorfs-csi
      priorityClassName: system-cluster-critical
      terminationGracePeriodSeconds: 3
      containers:
      
        - name: controller
          image: {{ .Values.csiDriver.image.auristorRegistry }}/auristorfs-csi:{{ .Values.csiDriver.image.auristorCsiVersion }}
          imagePullPolicy: {{ .Values.csiDriver.image.csiDriverImagePullPolicy | quote }}
          securityContext:
            privileged: true

          envFrom: 
          - configMapRef:
              name: auristorfs-csi-controller-config
          env:
            - name: SERVICE_TYPE
              value: "Controller"              
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_DOMAIN_SOCKET
              value: "/csi/csi.sock"
          ports:
          # - containerPort: 9898
          #   name: healthz
          #   protocol: TCP
          # livenessProbe:                  # TODO - Implement later
          #   failureThreshold: 10
          #   httpGet:
          #     path: /healthz
          #     port: healthz
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 3
          #   periodSeconds: 2

          volumeMounts:

            - mountPath: /csi
              name: controller-socket-dir
            
            {{ if .Values.csiDriver.cacheManager.afsRootDir }}
            - mountPath: /root/afs
              name: afs-root
            {{ end }}
              
            - mountPath: /root/appVar
              name: app-var

        - name: csi-attacher
          image: {{ .Values.csiDriver.image.k8sSigStorageRegistry }}/csi-attacher:v3.4.0
          imagePullPolicy: {{ .Values.csiDriver.image.k8sSigStorageImagePullPolicy | quote }}
          securityContext:
            privileged: true          
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: controller-socket-dir   
            
        - name: csi-provisioner
          image: {{ .Values.csiDriver.image.k8sSigStorageRegistry }}/csi-provisioner:v3.1.0
          imagePullPolicy: {{ .Values.csiDriver.image.k8sSigStorageImagePullPolicy | quote }}
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            {{- if .Values.csiDriver.persistentVolumeNaming }}
            {{- if .Values.csiDriver.persistentVolumeNaming.volumeNamePrefix }}
            - --volume-name-prefix={{ .Values.csiDriver.persistentVolumeNaming.volumeNamePrefix}}
            {{ end }}
            {{ end }}
            {{- if .Values.csiDriver.debug }}
            {{- if .Values.csiDriver.debug.volumeNameUuidLength }}
            - --volume-name-uuid-length={{ .Values.csiDriver.debug.volumeNameUuidLength}} # DEBUG/TESTING ONLY -  Small value during testing/debugging, otherwise comment/remove arg
            {{ end }}
            {{ end }}
            - --extra-create-metadata=true # Include of PVC, PVC-Namespace and PV to be included in Controller.CreateVolume parameteters

          volumeMounts:
            - mountPath: /csi
              name: controller-socket-dir   

        - name: liveness-probe
          image: {{ .Values.csiDriver.image.k8sSigStorageRegistry }}/livenessprobe:v2.5.0
          imagePullPolicy: {{ .Values.csiDriver.image.k8sSigStorageImagePullPolicy | quote }}
          securityContext:
            privileged: true              
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=9898
          volumeMounts:
          - mountPath: /csi
            name: controller-socket-dir               

      volumes:
        - name: controller-socket-dir
          emptyDir: {}
          
        {{ if .Values.csiDriver.cacheManager.afsRootDir }}
        - name: afs-root
          hostPath:
            path: /afs 
        {{ end }}

        - name: app-var
          configMap:
            name: auristorfs-csi-node-config            
