
{{- if eq .Values.runArgs.platform "openshift-container-platform" }}
---
####################################
###     CSI Extra Permissions    ###
####################################

apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: Allow privileged
    release.openshift.io/create-only: "true"
  name: auristorfs-csi-uber
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
allowedCapabilities:
- 'SYS_ADMIN'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:auristorfs-csi
volumes:
- emptyDir
- hostPath
- secret  
- configMap
{{ end }}
