apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pvx
spec:
  volumeName: pv-pvx
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi  # Ignored
  selector: 
    matchLabels: 
      volume: pv-pvx